# Generated by Django 5.2.8 on 2025-12-01 11:21

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationTempData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('non_editable_data', models.JSONField(blank=True, null=True)),
                ('ai_data', models.JSONField(blank=True, null=True)),
                ('manual_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('job_id', models.BigIntegerField(blank=True, null=True)),
                ('ai_manual_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classification_temp_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('params', models.JSONField(blank=True, null=True)),
                ('ai_data', models.JSONField(blank=True, null=True)),
                ('ai_filepath', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'job_requests',
            },
        ),
        migrations.CreateModel(
            name='MapLogColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('alias_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
            ],
            options={
                'db_table': 'column_map',
            },
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'upload_log',
            },
        ),
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_id', models.IntegerField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_data', models.JSONField(blank=True, null=True)),
                ('upload_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='modules_file_uploads.uploadlog')),
            ],
            options={
                'db_table': 'upload_data',
            },
        ),
    ]
