# Generated by Django 5.2.8 on 2025-11-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_file_uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddata',
            name='upload_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='modules_file_uploads.uploadlog'),
        ),
    ]
