# Generated by Django 5.2.8 on 2025-12-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_file_uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='statistics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
