# Generated by Django 5.2.8 on 2025-11-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_file_uploads', '0002_uploaddata_upload_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddata',
            name='module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
