# Generated by Django 5.2.8 on 2025-12-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_file_uploads', '0002_jobrequest_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
