# Generated by Django 5.2.8 on 2025-12-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_file_uploads', '0003_jobrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='status',
        ),
    ]
