# Generated by Django 5.2.8 on 2025-11-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_file_uploads', '0003_uploaddata_module_uploadlog_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_log_id', models.UUIDField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_data',
            },
        ),
    ]
