# Generated by Django 5.2.8 on 2025-12-03 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_file_uploads', '0004_remove_jobrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='account_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='job_id',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='upload_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
