# Generated by Django 5.2.8 on 2025-11-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_file_uploads', '0004_aidata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maplogcolumn',
            table='column_map',
        ),
    ]
